# Generated by Django 2.0.3 on 2018-03-24 03:06

import ToolrAPI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateTimeField(default=ToolrAPI.models.get_expire_time)),
                ('token', models.BinaryField(default=ToolrAPI.models.get_token)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('google_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='authtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolrAPI.UserProfile'),
        ),
    ]
