# Generated by Django 2.0.3 on 2018-03-24 03:31

import ToolrAPI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0002_auto_20180324_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.TextField(default=ToolrAPI.models.get_token),
        ),
    ]
