# Generated by Django 2.0.3 on 2018-03-28 01:18

import ToolrAPI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0003_auto_20180324_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recipient', models.ForeignKey(on_delete=models.SET(ToolrAPI.models.get_sentinel_user), related_name='recipient', to='ToolrAPI.UserProfile')),
                ('sender', models.ForeignKey(on_delete=models.SET(ToolrAPI.models.get_sentinel_user), related_name='sender', to='ToolrAPI.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('category', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField(default=0)),
                ('location_lon', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('lent_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_borrower', to='ToolrAPI.UserProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_owner', to='ToolrAPI.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='ToolrAPI.Tool'),
        ),
    ]
