# Generated by Django 2.0 on 2018-04-05 02:34

import ToolrAPI.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0005_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=models.SET(ToolrAPI.models.get_sentinel_user), related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(ToolrAPI.models.get_sentinel_user), related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='lent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
