# Generated by Django 2.0 on 2018-04-05 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0006_auto_20180405_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='lent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tool_borrower', to=settings.AUTH_USER_MODEL),
        ),
    ]
