# Generated by Django 2.0 on 2018-04-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0010_userprofile_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
    ]
