# Generated by Django 2.0 on 2018-04-07 21:51

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0011_remove_userprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='pic'),
        ),
    ]
