# Generated by Django 2.0 on 2018-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0013_auto_20180409_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='partner_display',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
