# Generated by Django 2.0.3 on 2018-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0014_conversation_partner_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sendAt',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
