# Generated by Django 2.0.3 on 2018-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0015_message_sendat'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='adress',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default='1970-01-01'),
        ),
    ]
