# Generated by Django 2.0.3 on 2018-04-17 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ToolrAPI', '0016_auto_20180416_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('returned', models.BooleanField(default=False)),
                ('rating_owner', models.IntegerField(default=-1)),
                ('rating_borrower', models.IntegerField(default=-1)),
                ('date', models.DateField(auto_now_add=True)),
                ('borrowing_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_borrower', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_tool', to='ToolrAPI.Tool')),
                ('tool_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='loan',
            unique_together={('tool', 'borrowing_user', 'date')},
        ),
    ]
