# Generated by Django 2.0 on 2018-04-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0018_auto_20180418_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(null=True),
        ),
    ]
