# Generated by Django 2.0 on 2018-04-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolrAPI', '0018_auto_20180418_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='proposal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='ToolrAPI.Loan'),
        ),
    ]
